'use strict';
const $=s=>document.querySelector(s);
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',chart:'<path d="M4 4v16h17M8 15v-3m5 3V7m5 8v-5"/>',network:'<rect x="8" y="3" width="8" height="5" rx="1"/><rect x="2" y="16" width="7" height="5" rx="1"/><rect x="15" y="16" width="7" height="5" rx="1"/><path d="M12 8v4H5v4m7-4h7v4"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',cycle:'<path d="M20 7a9 9 0 0 0-15-1L2 9m0-6v6h6m-4 8a9 9 0 0 0 15 1l3-3m0 6v-6h-6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.2"/>',monitor:'<rect x="3" y="4" width="18" height="12" rx="2"/><path d="M12 16v4m-4 0h8"/>',chair:'<path d="M6 12V4h12v8M4 12h16v5H4zm2 5v4m12-4v4"/>',book:'<path d="M12 5C8 2 4 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-4-2-7-1-10 1zm0 0v15"/>',box:'<path d="m12 2 9 5v10l-9 5-9-5V7zm-9 5 9 5 9-5m-9 5v10M7 4.5l9 5"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',leaf:'<path d="M20 3C8 1 2 8 6 15c6 7 16-1 14-12ZM3 22l13-14"/>',school:'<path d="m2 9 10-6 10 6M4 9v12h16V9M9 21v-7h6v7M7 10h1m8 0h1"/>',check:'<path d="m5 12 4 4L19 6"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.box}</svg>`;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number(x).toLocaleString('en-IN',{maximumFractionDigits:2});
let db=null, selection=null, sequence=0, lastResult=[], toastTimer;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
async function api(path,data){const res=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-ReLoop-Token':db.token},body:JSON.stringify(data)}:{});const body=await res.json();if(!res.ok)throw Error(body.error||'Something went wrong. Try reloading.');return body;}
function view(name){if(!['exchange','impact','partners'].includes(name))name='exchange';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('.nav').forEach(el=>{el.classList.toggle('active',el.dataset.view===name);el.setAttribute('aria-current',el.dataset.view===name?'page':'false');});$('#crumb').textContent={exchange:'Resource exchange',impact:'Reuse impact',partners:'Partner network'}[name];history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'auto'});}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>view(el.dataset.view)));
$('.brand').addEventListener('click',e=>{e.preventDefault();view('exchange');});
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,5500);}
function categoryIcon(m){return m.category==='Electronics'?'monitor':m.category==='Furniture'?'chair':m.category==='Stationery'?'book':'box';}
async function refresh(){db=await api('/api/bootstrap');const existing=$('#recipient').value;$('#recipient').innerHTML=db.partners.filter(p=>p.approved).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('#recipient').value=existing||'SCHOOL01';$('#listing-count').textContent=db.inventory.filter(i=>i.quantity>0).length;renderImpact();renderPartners();}
async function search(event){if(event)event.preventDefault();if(!$('#search-form').reportValidity())return;const run=++sequence;$('#search-error').textContent='';$('#search-button').disabled=true;$('#search-button').textContent='Finding matches…';const query={query:$('#query').value,quantity:Number($('#quantity').value),radius:Number($('#radius').value),recipient:$('#recipient').value,repair:$('#repair').checked};try{const result=await api('/api/match',query);if(run!==sequence)return;lastResult=result.matches.map(m=>({...m,recipient:query.recipient,requested:query.quantity}));$('#results-title').textContent=`${lastResult.length} matching resource${lastResult.length===1?'':'s'}`;if(!lastResult.length){$('#results').innerHTML=`<div class="empty">${icon('search')}<h3>${result.status==='clarify'?'Let’s make the request clearer':'No matches in this search'}</h3><p>${esc(result.message)}</p></div>`;return;}$('#results').innerHTML=lastResult.map((m,index)=>`<article class="resource-card"><div class="card-top"><span class="category-icon">${icon(categoryIcon(m))}</span><div><span class="category-label">${esc(m.category)}</span><span class="rank">${index===0?'TOP TEXT MATCH':`MATCH ${String(index+1).padStart(2,'0')}`}</span></div></div><div class="card-body"><h3>${esc(m.title)}</h3><div class="owner">${icon('pin')}${esc(m.department)}</div><div class="details"><span>${num(m.quantity)} available</span><span>${num(m.distance_km)} km away</span><span class="condition">${m.condition==='working'?'Working condition':'Repair needed'}</span></div><div class="match-evidence">Matched words: <strong>${m.matched_terms.map(esc).join(', ')}</strong><br>Text similarity ${Number(m.similarity).toFixed(2)} · Staff inspection required</div><div class="card-bottom"><div class="supply">${m.offered_quantity} of ${query.quantity} units<small>${m.remaining_need?`${m.remaining_need} more still needed`:'Requested quantity available'}</small></div><button class="review" data-match="${index}">Review transfer ↗</button></div></div></article>`).join('');document.querySelectorAll('[data-match]').forEach(b=>b.addEventListener('click',()=>openTransfer(lastResult[Number(b.dataset.match)])));}catch(error){if(run!==sequence)return;$('#search-error').textContent=error.message;$('#results').innerHTML='';$('#results-title').textContent='Search could not complete';}finally{if(run===sequence){$('#search-button').disabled=false;$('#search-button').innerHTML='Find matches <span>↗</span>';}}}
$('#search-form').addEventListener('submit',search);document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{$('#query').value=b.dataset.query;search();}));
function renderImpact(){const s=db.summary;const stats=[['Units kept in use',num(s.units_reused),'Recorded transfer quantities','cycle'],['Resources for schools',num(s.school_units_supplied),'Units supplied to school partners','school'],['Estimated reused mass',num(s.estimated_mass_reused_kg)+' kg','Based on sample item weights','leaf'],['Estimated net savings','INR '+num(s.estimated_net_savings_inr),'Entered benchmarks, less costs','chart'],['Completed transfers',num(s.confirmed_demo_transfers),'Confirmed local records','check'],['Partners served',num(s.recipient_partners_served),'Distinct recipient institutions','network']];$('#metrics').innerHTML=stats.map(([title,value,note,i])=>`<article class="metric"><div class="metric-head"><span>${title}</span>${icon(i)}</div><strong>${value}</strong><small>${note}</small></article>`).join('');$('#history').innerHTML=db.transfers.length?db.transfers.slice(-10).reverse().map(t=>`<div class="history-row"><span class="category-icon">${icon('check')}</span><div><strong>${esc(t.title)}</strong><small>${esc(t.id)} · To ${esc(t.recipient_name||'Demo Campus')}</small><small>${num(t.estimated_mass_reused_kg)} kg estimated reused mass</small></div><span>${num(t.quantity)} units<small>INR ${num(t.estimated_net_savings)}</small></span></div>`).join(''):`<div class="empty">${icon('cycle')}<h3>Your first transfer starts a story.</h3><p>Find a resource, review it, and record a demo transfer to see your reuse activity here.</p><button class="outline" id="empty-find">Find resources ↗</button></div>`;$('#empty-find')?.addEventListener('click',()=>view('exchange'));}
function renderPartners(){$('#partner-cards').innerHTML=db.partners.map(p=>`<article class="partner"><span class="category-icon">${icon(p.type==='school'?'school':'network')}</span><h2>${esc(p.name)}</h2><p>${esc(p.type.toUpperCase())} · ${esc(p.id)}</p><span class="status ${p.approved?'':'pending'}">${p.approved?'Approved demo partner':'Awaiting review'}</span></article>`).join('');}
function openTransfer(m){selection=m;$('#transfer-form').reset();$('#transfer-title').textContent='A new home for this resource.';const recipient=db.partners.find(p=>p.id===m.recipient);$('#transfer-context').innerHTML=`<div class="transfer-context"><strong>${esc(m.title)}</strong><span>${esc(m.department)} → ${esc(recipient.name)}</span><span>${num(m.quantity)} available · ${num(m.distance_km)} km collection distance</span></div>`;$('#transfer-quantity').value=m.offered_quantity;$('#transfer-quantity').max=m.quantity;$('#transfer-error').textContent='';$('#confirm-button').disabled=false;$('#confirm-button').textContent='Confirm demo transfer ↗';estimate();$('#transfer-dialog').showModal();}
function estimate(){const value=Number($('#transfer-quantity').value)*(Number($('#price').value)-Number($('#refurbishment').value))-Number($('#transport').value);$('#estimate-value').textContent=Number.isFinite(value)?'INR '+num(value):'Check amounts';}
['transfer-quantity','price','transport','refurbishment'].forEach(id=>$('#'+id).addEventListener('input',estimate));
function closeDialog(){if(!$('#confirm-button').disabled)$('#transfer-dialog').close();}
$('#close-dialog').addEventListener('click',closeDialog);$('#cancel-dialog').addEventListener('click',closeDialog);$('#transfer-dialog').addEventListener('cancel',e=>{if($('#confirm-button').disabled)e.preventDefault();});
$('#transfer-form').addEventListener('submit',async e=>{e.preventDefault();if(!selection||!$('#transfer-form').reportValidity())return;$('#transfer-error').textContent='';$('#confirm-button').disabled=true;$('#confirm-button').textContent='Recording…';let committed=false;try{const data=await api('/api/transfer',{item:selection.id,recipient:selection.recipient,quantity:Number($('#transfer-quantity').value),price:Number($('#price').value),transport:Number($('#transport').value),refurbishment:Number($('#refurbishment').value),inspected:$('#inspected').checked});committed=true;$('#transfer-dialog').close();selection=null;await refresh();await search();view('impact');toast(`Transfer ${data.id} recorded. ${data.quantity} units have a new home.`);}catch(error){if(committed){toast('Transfer saved. Reload the app to refresh your summary.');}else{$('#transfer-error').textContent=error.message;}}finally{$('#confirm-button').disabled=false;$('#confirm-button').textContent='Confirm demo transfer ↗';}});
(async()=>{try{await refresh();await search();view(location.hash.slice(1)||'exchange');}catch(error){$('#results-title').textContent='Could not open the workspace';$('#search-error').textContent=error.message+' Keep the Python server running and reload this page.';}})();
